Repository Sanchitbajaj02/Hacktoberfest-2022-firstPush, pull requests merged in 2022-10, with the labels that each got.

#2 added java/deque
  .DS_Store
  Java/Array Deque/Main.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#4 some patterns in java
  Java/Array Deque/binaryLeftAngleTriangle.java
  Java/Array Deque/butterflyPattern.java
  Java/Array Deque/diamond.java
  Java/Array Deque/halfPryamid.java
  Java/Array Deque/hollowButterfly.java
  Java/Array Deque/hollowRhombus.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#3 2dArray
  Java/Array2d/FindElementInSortedArray.java
  Java/Array2d/RingRotate.java
  Java/Array2d/Rotateby90degree.java
  Java/Array2d/SaddlePoint.java
  Java/Array2d/StateOfWakanda2.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#5 Create reverseArray.java
  reverseArray.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#6 added leetcode question 832
  Java/Array2d/FlippingAnImage.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#7 Area
  Java/Array2d/Area.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#8 Create Fibonacci.java
  Fibonacci.java
Labels: hacktoberfest, hacktoberfest-accepted

#9 Factorial Using Recursion
  Cpp/factorial_Rec.cpp
  Cpp/factorial_Rec.exe
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#10 smallest greatest element 2d array code
  Java/Array2d/smallestGreatestElement
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
